- name: Set distro-specific package names
  ansible.builtin.include_vars:
    file: "{{ lookup('first_found', params) }}"
    name: "package"
  vars:
    params:
      files:
        - "packages_{{ ansible_facts['distribution'] }}.yml"
        - "packages_default.yml"

- name: Ensure docker is installed
  ansible.builtin.package:
    name: "{{ package.docker }}"
    state: present

- name: Ensure docker is enabled
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    masked: no
    state: started

- name: Ensure the gin service group exists
  ansible.builtin.group:
    name: ginservice
    state: present
  register: ginservice_group

- name: Ensure gin user exists
  ansible.builtin.user:
    name: ginuser
    group: ginservice
    groups: [docker]
    password_lock: yes
  register: ginuser_user

- name: Ensure non-root docker admin user exists
  ansible.builtin.user:
    name: dockeradmin
    group: docker
    password_lock: yes
    groups: [ginservice]

- name: Ensure pip is installed
  ansible.builtin.package:
    name: [python3-pip]
    state: present

- name: Ensure latest version of docker-compose is installed for dockeradmin
  become: true
  become_user: dockeradmin
  ansible.builtin.pip:
    name: docker-compose
    extra_args: --user
