---
- name: Ensure gin service directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0775'
    owner: ginuser
    group: ginservice
  loop:
    - /srv/gin
    - /srv/gin/config
    - /srv/gin/volumes
    - /srv/gin/gindata
    - /srv/gin/config/gogs
    - /srv/gin/config/gogs/conf
    - /srv/gin/config/gogs/notice
    - /srv/gin/config/postgres
    - /srv/gin/volumes/ginweb
    - /srv/gin/gindata/gin-repositories
    - /srv/gin/gindata/git-postgresdb
    - /srv/gin/gin-dockerfile

- name: Ensure gin docker-compose env exists
  ansible.builtin.copy:
    dest: /srv/gin/gin-dockerfile/.env
    owner: ginuser
    group: ginservice
    mode: '0664'
    content: COMPOSE_PROJECT_NAME=gin

- name: Ensure postgres secrets file exists
  ansible.builtin.template:
    dest: /srv/gin/config/postgres/pgressecrets.env
    src: pgressecrets.env
    owner: ginuser
    group: ginservice
    mode: '0660'

- name: Ensure docker-compose config exists
  ansible.builtin.template:
    dest: /srv/gin/gin-dockerfile/docker-compose.yml
    src: docker-compose.yml.jinja2
    owner: ginuser
    group: ginservice
    mode: '0664'

- name: Check if gin config exists
  ansible.builtin.stat:
    path: /srv/gin/config/gogs/conf/app.ini
  register: gin_config_stat

- name: Ensure gin config has proper rights if it exists
  ansible.builtin.file:
    path: /srv/gin/config/gogs/conf/app.ini
    mode: '0664'
    owner: ginuser
    group: ginservice
  when: gin_config_stat.stat.exists

- name: Ensure systemd service definition file is present
  ansible.builtin.copy:
    dest: /etc/systemd/system/gin.service
    src: gin.service
    mode: '0644'
